Parameters:
    ID:
      Type: String
    
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId:
           Ref: myVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: CentOS
      ImageId: ami-0ddc70e50205f89b6
      VolumeSize: "40"
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
    
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: CentOS2
      ImageId: ami-0ddc70e50205f89b6
      VolumeSize: "40"
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
  