version: 2.1

jobs:  
  deploy-infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: deploy infrastructure
            command: |
              aws cloudformation deploy \
                --template-file .circleci/files/backend.yml \
                --tags project=Challenge \
                --stack-name "stack-${CIRCLE_WORKFLOW_ID:0:7}" 
        - run: 
            name: depoy infrastructure
            command: |
              aws cloudformation deploy \
                --template-file .circleci/files/frontend.yml \
                --tags project=Challenge \
                --stack-name "stack-${CIRCLE_WORKFLOW_ID:0:7}" 



workflows:
  default:
    jobs:
        - deploy-infrastructure
